# Generated by Django 5.2.10 on 2026-02-03 08:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('planted_at', models.DateTimeField()),
                ('variation', models.CharField(choices=[('red', 'Red'), ('purple', 'Purple'), ('green', 'Green')], max_length=10)),
                ('seed', models.PositiveIntegerField()),
                ('owner_token', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
